---
apiVersion: v1
kind: Pod
metadata:
  name: pod-l3
  labels:
    app: web
spec:
  containers:
    - name: cont-l3
      image: k8s-tutorial/lesson-1:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 3333
          hostPort: 3333